-- app_data 
CREATE USER app_data IDENTIFIED BY "a7IrvJ0C8vnA239"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_code 
CREATE USER app_code IDENTIFIED BY "sEYUsQRiiMks2wn"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_admin
CREATE USER app_admin IDENTIFIED BY "IkyOVDtqC5yFMmB"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_user
CREATE USER app_user IDENTIFIED BY "Z99m4RuCdla3dae"
ENABLE EDITIONS;